-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for BigEye EWR Plugin
--
-- This configuration is tailored for a mission generated by DCS Retribution
-- see https://github.com/dcs-retribution/dcs-retribution
-------------------------------------------------------------------------------------------------------------------------------------------------------------


-- BigEye EWR Plugin - configuration
if dcsRetribution then
    -- retrieve specific options values
    if dcsRetribution.plugins then
        if dcsRetribution.plugins.bigeye then
            env.info("DCSRetribution|BigEye EWR - Setting Up")
            EWR.displayMessageTime = dcsRetribution.plugins.bigeye.displayMessageTime
            EWR.highReportFrequencyPreference = dcsRetribution.plugins.bigeye.highReportFrequencyPreference
            EWR.defaultReportFrequencyPreference = dcsRetribution.plugins.bigeye.defaultReportFrequencyPreference
            EWR.lowReportFrequencyPreference = dcsRetribution.plugins.bigeye.lowReportFrequencyPreference
            EWR.gciReportFrequency = dcsRetribution.plugins.bigeye.gciReportFrequency
            EWR.defaultEnableReportPreference = dcsRetribution.plugins.bigeye.defaultEnableReportPreference
            EWR.maxReportUnits = dcsRetribution.plugins.bigeye.maxReportUnits
            EWR.isAvailableNCTR = dcsRetribution.plugins.bigeye.isAvailableNCTR
            EWR.blueHasDLINK = dcsRetribution.plugins.bigeye.blueHasDLINK
            EWR.blueHasRWR = dcsRetribution.plugins.bigeye.blueHasRWR
            EWR.blueHasIRST = dcsRetribution.plugins.bigeye.blueHasIRST
            EWR.redHasDLINK = dcsRetribution.plugins.bigeye.redHasDLINK
            EWR.redHasRWR = dcsRetribution.plugins.bigeye.redHasRWR
            EWR.redHasIRST = dcsRetribution.plugins.bigeye.redHasIRST
            EWR.reportUnitNameNATO = dcsRetribution.plugins.bigeye.reportUnitNameNATO
            -- The main script built the INTEL fusion at load time, BEFORE these
            -- coalition sensor options existed, so re-apply the detection sensor
            -- types now that datalink/RWR/IRST are set (else the UI toggles no-op).
            if blueIntel then
                blueIntel:SetDetectionTypes(true, true, true, EWR.blueHasIRST, EWR.blueHasRWR, EWR.blueHasDLINK)
            end
            if redIntel then
                redIntel:SetDetectionTypes(true, true, true, EWR.redHasIRST, EWR.redHasRWR, EWR.redHasDLINK)
            end
        end
    end
end
