"""Real METAR weather from the ATMOS-X CLI.

The CLI is a third-party executable that talks to the network, so nothing here runs it:
what is tested is everything around it -- reading what it writes, picking the station to
ask for, choosing which day to ask about, and copying the result onto a mission.
"""

from __future__ import annotations

import csv
from datetime import datetime
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import pytest
from dcs.weather import Weather

from game.timeofday import TimeOfDay

from dcs.cloud_presets import CLOUD_PRESETS
from dcs.weather import Weather as PydcsWeather

from game.weather.atmosxliveweather import (
    LiveWeather,
    PresetParseError,
    Station,
    apply_weather,
    choose_station,
    live_weather_for,
    parse_preset,
    preferred_airfields,
    stations_for_theater,
)

# Trimmed from a real "atmosx-cli metar LCLK --save" run: comments, the trailing
# "-- end of vdata" markers and the two top-level assignments the reader must cope with.
PRESET = """\
-- Weather preset: ATX - LCLK METAR
-- Generated by ATMOS-X CLI: 2026-08-19 11:30:07

vdata = {
    name = "ATX - LCLK METAR",
    atmosphere_type = 0,
    groundTurbulence = 0.0000,
    enable_dust = false,
    dust_density = 0,
    qnh = 758,
    season = {
        temperature = 31.0,
    },
    visibility = {
        distance = 80000,
    },
    wind = {
        atGround = { speed = 3.60, dir = 350, },
        at2000 = { speed = 4.32, dir = 350, },
        at8000 = { speed = 5.40, dir = 350, },
    },
    clouds = {
        preset = "none",
        thickness = 0,
        density = 0,
        base = 764,
        iprecptns = 0,
    },
    fog2 = {
        mode = 1,
        manual = {
        },
    },
} -- end of vdata
dtime = {
    date = {
        Year = 2026,
        Day = 19,
        Month = 8,
    },
    start_time = 43200,
} -- end of dtime
"""


def test_reads_both_top_level_blocks() -> None:
    """dtime is parsed and then ignored -- the mission always keeps its own clock."""
    parsed = parse_preset(PRESET)
    assert set(parsed) == {"vdata", "dtime"}
    assert parsed["vdata"]["qnh"] == 758
    assert parsed["vdata"]["clouds"]["preset"] == "none"
    assert parsed["vdata"]["enable_dust"] is False
    assert parsed["vdata"]["wind"]["atGround"] == {"speed": 3.6, "dir": 350}
    assert parsed["vdata"]["fog2"]["manual"] == {}


def test_a_malformed_preset_is_an_error_not_a_wrong_answer() -> None:
    with pytest.raises(PresetParseError):
        parse_preset("vdata = { qnh = ")


def test_the_observation_lands_on_the_mission() -> None:
    weather = Weather("Syria")
    apply_weather(weather, parse_preset(PRESET)["vdata"])
    assert weather.qnh == 758
    assert weather.season_temperature == 31.0
    assert weather.visibility_distance == 80000
    assert weather.wind_at_ground.speed == 3.6
    assert weather.wind_at_8000.direction == 350
    # A clear METAR: preset "none" means no preset, not a preset called "none".
    assert weather.clouds_preset is None
    assert weather.clouds_base == 0


def test_the_mission_can_still_be_written_out() -> None:
    """The regression that matters: DCS reads .name off the preset and validates the
    base against it, so a preset key left as a bare string kills mission generation."""
    for key, base in (("none", 764), ("Preset10", 2000)):
        vdata = parse_preset(PRESET)["vdata"]
        vdata["clouds"] = {
            "preset": key,
            "base": base,
            "thickness": 0,
            "density": 0,
            "iprecptns": 0,
        }
        weather = Weather("Syria")
        apply_weather(weather, vdata)
        assert isinstance(weather.dict(), dict)


def test_a_ceiling_outside_the_presets_range_is_clamped_not_fatal() -> None:
    """DCS refuses the mission outright; a METAR ceiling near the edge is common."""
    preset = CLOUD_PRESETS["Preset10"].value
    vdata = parse_preset(PRESET)["vdata"]
    vdata["clouds"] = {
        "preset": "Preset10",
        "base": 1,
        "thickness": 0,
        "density": 0,
        "iprecptns": 0,
    }
    weather = Weather("Syria")
    apply_weather(weather, vdata)
    assert weather.clouds_base >= preset.min_base
    assert isinstance(weather.dict(), dict)


def test_fields_a_metar_says_nothing_about_are_left_alone() -> None:
    """The preset is not a whole weather definition; what it omits the campaign keeps."""
    weather = Weather("Syria")
    halo, cyclones = weather.halo, weather.cyclones
    weather.type_weather = 2
    apply_weather(weather, parse_preset(PRESET)["vdata"])
    assert weather.halo is halo
    assert weather.cyclones is cyclones
    assert weather.type_weather == 2


# --- station selection -----------------------------------------------------------


@pytest.fixture
def cli(tmp_path: Path) -> Path:
    """A stand-in CLI: only its folder matters, for finding dcs_icao.csv beside it."""
    rows = [
        ["Map", "Airfield", "ICAO", ""],
        ["Syria", "Larnaca International", "LCLK", ""],
        ["Syria", "Adana Şakirpaşa Airport", "LTAF", ""],
        ["Syria", "Rayak Air Base", "OLRA", ""],
        ["Caucasus", "Batumi", "UGSB", ""],
        ["Syria", "No Station", "", ""],
    ]
    with (tmp_path / "dcs_icao.csv").open("w", newline="", encoding="utf-8-sig") as f:
        csv.writer(f).writerows(rows)
    exe = tmp_path / "atmosx-cli.exe"
    exe.write_text("", encoding="utf-8")
    return exe


def test_only_stations_on_this_terrain_and_only_real_ones(cli: Path) -> None:
    stations = stations_for_theater(cli, "Syria")
    assert [s.icao for s in stations] == ["LCLK", "LTAF", "OLRA"]
    assert Station("UGSB", "Batumi") not in stations


def test_an_airfield_that_reports_is_used(cli: Path) -> None:
    station = choose_station(cli, "Syria", ["Larnaca International"])
    assert station is not None and station.icao == "LCLK"


def test_names_match_across_accents_and_suffixes(cli: Path) -> None:
    """ED writes "Adana Sakirpasa", ATMOS-X writes "Adana Şakirpaşa Airport"."""
    station = choose_station(cli, "Syria", ["Adana Sakirpasa"])
    assert station is not None and station.icao == "LTAF"


def test_a_base_with_no_station_falls_back_to_the_nearest_that_has_one(
    cli: Path,
) -> None:
    positions = {
        "Beirut": SimpleNamespace(x=0.0, y=0.0),
        "Rayak Air Base": SimpleNamespace(x=1000.0, y=0.0),
        "Larnaca International": SimpleNamespace(x=500_000.0, y=0.0),
    }
    station = choose_station(cli, "Syria", ["Beirut"], positions)
    assert station is not None and station.icao == "OLRA"


def test_without_positions_it_still_answers(cli: Path) -> None:
    station = choose_station(cli, "Syria", ["Nowhere"])
    assert station is not None


def test_a_terrain_atmosx_does_not_cover_has_no_station(cli: Path) -> None:
    assert choose_station(cli, "Marianas", ["Andersen"]) is None


def test_a_missing_csv_is_survivable(tmp_path: Path) -> None:
    assert stations_for_theater(tmp_path / "atmosx-cli.exe", "Syria") == []


def test_the_bases_are_read_before_the_coalitions_are_wired() -> None:
    """`Game.__init__` generates conditions before `ControlPoint.finish_init` runs.

    Reading `captured` there raised and took New Game down with it, so the preference
    list comes from `starting_coalition` instead.
    """

    class NotYetInitialized:
        def __init__(self, name: str, blue: bool) -> None:
            self.name = name
            self.starting_coalition = SimpleNamespace(is_blue=blue)

        @property
        def captured(self) -> Any:
            raise RuntimeError("ControlPoint not fully initialized: coalition not set")

    theater = SimpleNamespace(
        controlpoints=[
            NotYetInitialized("Incirlik", True),
            NotYetInitialized("Hama", False),
        ]
    )
    assert preferred_airfields(theater) == ["Incirlik"]


def test_a_theater_with_no_control_points_asks_for_nothing() -> None:
    assert preferred_airfields(SimpleNamespace()) == []


def test_a_failure_inside_the_lookup_never_stops_the_turn() -> None:
    """The module header promises this. Until New Game crashed it was not enforced."""

    class Exploding:
        @property
        def atmosx_live_weather(self) -> bool:
            raise RuntimeError("the CLI, the network, or a half-built theater")

    assert live_weather_for(SimpleNamespace(), Exploding()) is None


# --- the settings only apply when they can do something -------------------------


def test_the_atmosx_settings_are_gated_on_that_pack_being_selected() -> None:
    """A knob that quietly does nothing is worse than one visibly greyed out.

    The fork gates dependants with ``enabled_when`` (greys the control and its
    label, live across pages via SettingsDependencyHub) rather than upstream's
    separate hiding mechanism, so this pins the dependency rather than a predicate.
    """
    from game.settings import Settings
    from game.settings.settings import CloudPresetPack, MISSION_GENERATION_PAGE

    guarded = {
        name: description
        for name, description in Settings.fields(MISSION_GENERATION_PAGE, "Weather")
        if name.startswith("atmosx_")
    }
    assert set(guarded) == {
        "atmosx_live_weather",
        "atmosx_cli_path",
        "atmosx_metar_station",
    }
    for description in guarded.values():
        assert description.enabled_when == (
            "cloud_preset_pack",
            CloudPresetPack.ATMOSX,
        )


def test_the_pack_and_its_knobs_are_laid_out_together() -> None:
    """A dependency the player cannot see next to its master reads as broken."""
    from game.settings.settings import FIELD_LAYOUT, MISSION_GENERATION_PAGE

    for name in (
        "cloud_preset_pack",
        "atmosx_live_weather",
        "atmosx_cli_path",
        "atmosx_metar_station",
    ):
        assert FIELD_LAYOUT[name] == (MISSION_GENERATION_PAGE, "Weather")


# --- the observation as the turn's own weather -----------------------------------


def test_the_observation_becomes_the_weather_the_game_reads() -> None:
    """The kneeboard, the active runway and the carrier all read this, not the .miz."""
    weather = LiveWeather("LCLK", parse_preset(PRESET)["vdata"])

    assert round(weather.atmospheric.qnh.mm_hg) == 758
    assert weather.atmospheric.temperature_celsius == 31.0
    assert weather.atmospheric.turbulence_per_10cm == 0.0
    assert weather.wind.at_0m.direction == 350
    assert weather.wind.at_0m.speed == 3.6
    assert weather.wind.at_8000m.speed == 5.4
    # "none" with nothing to draw is a clear sky, which is what the rest of the game
    # understands by no clouds.
    assert weather.clouds is None
    assert weather.fog is None
    assert weather.archetype.id == "clear"


def test_a_named_preset_survives_into_the_model() -> None:
    vdata = parse_preset(PRESET)["vdata"]
    vdata["clouds"] = {
        "preset": "Preset10",
        "base": 2000,
        "thickness": 1200,
        "density": 6,
        "iprecptns": 1,
    }
    weather = LiveWeather("LCLK", vdata)
    assert weather.clouds is not None
    assert weather.clouds.preset is not None
    assert weather.clouds.preset.name == CLOUD_PRESETS["Preset10"].value.name
    assert weather.clouds.base == 2000
    assert weather.clouds.precipitation is PydcsWeather.Preceptions.Rain
    assert weather.archetype.id == "raining"


def test_a_preset_this_dcs_does_not_have_is_not_fatal() -> None:
    """A pack the player has not installed must not take the campaign down with it."""
    vdata = parse_preset(PRESET)["vdata"]
    vdata["clouds"] = {
        "preset": "Preset9999",
        "base": 900,
        "thickness": 0,
        "density": 4,
    }
    weather = LiveWeather("LCLK", vdata)
    assert weather.clouds is not None and weather.clouds.preset is None
    assert weather.clouds.base == 900


def test_the_mission_still_gets_what_the_model_cannot_hold() -> None:
    """visibility distance and dust have nowhere to live but the mission itself."""
    vdata = parse_preset(PRESET)["vdata"]
    vdata["visibility"] = {"distance": 4200}
    vdata["enable_dust"] = True
    vdata["dust_density"] = 3
    mission_weather = Weather("Syria")
    apply_weather(mission_weather, LiveWeather("LCLK", vdata).vdata)
    assert mission_weather.visibility_distance == 4200
    assert mission_weather.enable_dust is True
    assert mission_weather.dust_density == 3


def test_no_observation_leaves_the_turn_with_generated_weather(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    import game.weather.atmosxliveweather as module

    monkeypatch.setattr(module, "fetch_observation", lambda theater, settings: None)
    assert module.live_weather_for(object(), object()) is None


# --- the fork couplings ----------------------------------------------------------
#
# Upstream #927 hooks a single call site (`Conditions.generate`) because upstream
# re-rolls the weather from scratch every turn. The fork does not: §47 marches one
# clock and evolves the sky from the previous turn, §67 reads that sky to plan. All
# three couplings are pinned here -- each was a real defect in the straight port.


def _seasonal() -> Any:
    from game.theater.seasonalconditions import (
        Season,
        SeasonalConditions,
        WeatherTypeChances,
    )

    chances = WeatherTypeChances(
        thunderstorm=1.0, raining=1.0, cloudy=1.0, clear_skies=1.0
    )
    return SeasonalConditions(
        summer_avg_pressure=30.0,
        winter_avg_pressure=30.0,
        summer_avg_temperature=25.0,
        winter_avg_temperature=5.0,
        temperature_day_night_difference=10.0,
        high_avg_yearly_turbulence_per_10cm=1.0,
        low_avg_yearly_turbulence_per_10cm=0.1,
        solar_noon_turbulence_per_10cm=0.5,
        midnight_turbulence_per_10cm=0.1,
        weather_type_chances={season: chances for season in Season},
    )


def _theater() -> Any:
    from game.theater.daytimemap import DaytimeMap

    daytime = DaytimeMap(
        dawn=(datetime(2020, 1, 1, 6).time(), datetime(2020, 1, 1, 8).time()),
        day=(datetime(2020, 1, 1, 8).time(), datetime(2020, 1, 1, 16).time()),
        dusk=(datetime(2020, 1, 1, 16).time(), datetime(2020, 1, 1, 20).time()),
        night=(datetime(2020, 1, 1, 20).time(), datetime(2020, 1, 1, 23).time()),
    )
    return SimpleNamespace(seasonal_conditions=_seasonal(), daytime_map=daytime)


def _stormy_live_weather() -> LiveWeather:
    vdata = parse_preset(PRESET)["vdata"]
    vdata["clouds"] = {
        "preset": "Preset10",
        "base": 2000,
        "thickness": 1200,
        "density": 9,
        "iprecptns": 2,
    }
    return LiveWeather("LCLK", vdata)


def test_the_turn_after_a_real_observation_still_generates() -> None:
    """§47's ladder is a list of the four generated classes; LiveWeather is on none
    of them, so taking its class raised StopIteration on the next turn advance."""
    from game.weather.conditions import Conditions

    theater = _theater()
    previous = Conditions(
        time_of_day=TimeOfDay.Day,
        start_time=datetime(2020, 6, 15, 8, 0),
        weather=_stormy_live_weather(),
    )
    advanced = Conditions.advance(previous, theater)
    assert advanced.weather is not None
    assert advanced.start_time > previous.start_time


def test_the_next_turn_evolves_from_the_sky_that_was_actually_flown() -> None:
    """Not merely "does not crash": a live thunderstorm has to bias the next turn
    the way a generated one would, or the observation breaks the weather's memory."""
    from game.weather.conditions import Conditions
    from game.weather.weather import Thunderstorm

    assert Conditions._ladder_type(_stormy_live_weather()) is Thunderstorm


def test_live_weather_reaches_every_turn_not_only_the_first(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Turns 2+ come through `advance`, so hooking only `generate` would leave the
    feature working once and never again."""
    import game.weather.conditions as conditions_module
    from game.weather.conditions import Conditions

    observed = _stormy_live_weather()
    monkeypatch.setattr(
        conditions_module, "live_weather_for", lambda theater, settings: observed
    )
    previous = Conditions(
        time_of_day=TimeOfDay.Day,
        start_time=datetime(2020, 6, 15, 8, 0),
        weather=observed,
    )
    advanced = Conditions.advance(previous, _theater(), object())  # type: ignore[arg-type]
    assert advanced.weather is observed
    # Without settings there is nothing to ask, and the generated sky stands.
    assert Conditions.advance(previous, _theater()).weather is not observed


def test_the_weather_aware_planner_sees_a_live_storm() -> None:
    """§67 tested isinstance(Raining, Thunderstorm); a LiveWeather is neither, so a
    real thunderstorm read as clear -- auto-recon flew and low-level attack stayed."""
    from game.fourteenth import weather_planning

    game = SimpleNamespace(
        settings=SimpleNamespace(weather_aware_planning=True),
        conditions=SimpleNamespace(weather=_stormy_live_weather()),
    )
    assert weather_planning.storm(game)  # type: ignore[arg-type]
    assert weather_planning.poor_visibility_weather(game)  # type: ignore[arg-type]
    assert weather_planning.recon_suppressed(game)  # type: ignore[arg-type]


def test_a_clear_observation_leaves_the_planner_alone() -> None:
    from game.fourteenth import weather_planning

    game = SimpleNamespace(
        settings=SimpleNamespace(weather_aware_planning=True),
        conditions=SimpleNamespace(
            weather=LiveWeather("LCLK", parse_preset(PRESET)["vdata"])
        ),
    )
    assert not weather_planning.storm(game)  # type: ignore[arg-type]
    assert not weather_planning.recon_suppressed(game)  # type: ignore[arg-type]
