"""Operation Baltic Fury laydown guards.

The maritime GermanyCW counter-offensive (US CSG + F-22/F-15E vs Redfor Russia).
The `.miz` is generated by ``tools/build_baltic_fury_miz.py`` (reshaping the
all-vanilla ``red_tide.miz``); these pins catch a regeneration, an upstream sync,
or a pydcs re-save silently dropping the ownership, the carrier air-wing binding,
or the IADS/coastal/naval belt. Everything is validated at the ``load_theater``
depth (the fork's campaign-test convention) -- faction/TGO resolution needs the
mods enabled at New Game, which headless load can't exercise.
"""

from collections import Counter
from pathlib import Path

import yaml

from game import persistency
from game.campaignloader.campaign import Campaign
from game.fourteenth.victory import parse_victory
from game.theater import ConflictTheater

YAML = Path("resources/campaigns/operation_baltic_fury.yaml")

BLUE_FIELDS = {"Nordholz", "Bremen", "Hamburg"}
RED_FIELDS = {
    "Kastrup",
    "Laage",
    "Peenemunde",
    "Parchim",
    "Wismar",
    "Szczecin-Goleniow",
    "Bornholm",
    "Lubeck",
    "Barth",
}
CARRIER_NAME = "CVN-75 Harry S. Truman"


def _theater() -> tuple[Campaign, ConflictTheater]:
    campaign = Campaign.from_file(YAML)
    return campaign, campaign.load_theater(campaign.advanced_iads)


def test_campaign_loads_with_expected_control_points(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    _, theater = _theater()
    names = {cp.name for cp in theater.controlpoints}
    assert BLUE_FIELDS <= names, f"missing blue fields: {BLUE_FIELDS - names}"
    assert RED_FIELDS <= names, f"missing red fields: {RED_FIELDS - names}"
    assert CARRIER_NAME in names, "carrier control point missing / renamed"


def test_ownership(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    _, theater = _theater()
    by_name = {cp.name: cp for cp in theater.controlpoints}
    for name in BLUE_FIELDS | {CARRIER_NAME}:
        assert by_name[name].starting_coalition.is_blue, f"{name} must start BLUE"
    for name in RED_FIELDS:
        assert by_name[name].starting_coalition.is_red, f"{name} must start RED"


def test_air_wing_binds_including_the_carrier(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    campaign, theater = _theater()
    awc = campaign.load_air_wing_config(theater)
    by_name = {cp.name: squadrons for cp, squadrons in awc.by_location.items()}
    # The carrier wing keys off the carrier's NAME string (not a numeric id).
    assert CARRIER_NAME in by_name, "carrier air wing did not bind -- name-key drift"
    assert len(by_name[CARRIER_NAME]) == 6, "carrier should field 6 squadrons"
    # Nordholz = the 414th land wing (F-22 + F-15E).
    nordholz_types = {s.aircraft_type for s in by_name["Nordholz"] if s.aircraft_type}
    assert any("F-22" in t for t in nordholz_types)
    assert any("F-15E" in t for t in nordholz_types)


def test_iads_coastal_naval_belt(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    _, theater = _theater()
    belt: Counter[str] = Counter()
    for cp in theater.controlpoints:
        pl = cp.preset_locations
        for attr in (
            "long_range_sams",
            "medium_range_sams",
            "short_range_sams",
            "coastal_defenses",
            "ewrs",
            "missile_sites",
            "ships",
            "iads_command_center",
            "iads_connection_node",
            "iads_power_source",
            "factories",
            "ammunition_depots",
        ):
            belt[attr] += len(getattr(pl, attr))
    assert belt["long_range_sams"] == 11, "S-400 regiments + S-300 nodes"
    assert belt["medium_range_sams"] == 4, "forward MERAD screen"
    assert belt["short_range_sams"] == 9, "per-base point defense"
    assert belt["coastal_defenses"] == 5, "coastal anti-ship wall"
    assert belt["ewrs"] == 5
    assert belt["missile_sites"] == 1, "coastal SS-26 (SCUD hunt)"
    assert belt["ships"] == 3, "Baltic Fleet SAG"
    # advanced-IADS C2 cells (one trio per red hub).
    assert belt["iads_command_center"] == 4
    assert belt["iads_connection_node"] == 4
    assert belt["iads_power_source"] == 4
    assert belt["factories"] == 3
    assert belt["ammunition_depots"] == 3


def test_no_markers_leak_onto_the_spare_neutral_fields(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    _, theater = _theater()
    spares = {"Bienenfarm", "H FRG 09", "H FRG 12"}
    for cp in theater.controlpoints:
        if cp.name not in spares:
            continue
        pl = cp.preset_locations
        leaked = [
            attr
            for attr in dir(pl)
            if not attr.startswith("_")
            and isinstance(getattr(pl, attr), list)
            and getattr(pl, attr)
        ]
        assert not leaked, f"{cp.name} (inert spare) caught markers: {leaked}"


def test_victory_parses() -> None:
    data = yaml.safe_load(YAML.read_text(encoding="utf-8"))
    victory = parse_victory(data.get("victory"))
    assert victory is not None
    assert victory.win_when[0].capture_cps == ("Kastrup",)  # liberate Copenhagen
    assert victory.lose_when[0].lose_cps == ("Nordholz",)  # lose the bridgehead
