"""Operation Baltic Fury laydown guards.

The maritime GermanyCW counter-offensive (US CSG + F-22/F-15E vs Redfor Russia).
The `.miz` is generated by ``tools/build_baltic_fury_miz.py`` (reshaping the
all-vanilla ``red_tide.miz``); these pins catch a regeneration, an upstream sync,
or a pydcs re-save silently dropping the ownership, the carrier air-wing binding,
or the IADS/coastal/naval belt. Everything is validated at the ``load_theater``
depth (the fork's campaign-test convention) -- faction/TGO resolution needs the
mods enabled at New Game, which headless load can't exercise.
"""

from collections import Counter
from pathlib import Path
from typing import TYPE_CHECKING

import yaml

from game import persistency
from game.campaignloader.campaign import Campaign
from game.fourteenth.victory import parse_victory
from game.theater import ConflictTheater

YAML = Path("resources/campaigns/operation_baltic_fury.yaml")

BLUE_FIELDS = {"Nordholz", "Bremen", "Hamburg"}
RED_FIELDS = {
    "Kastrup",
    "Laage",
    "Peenemunde",
    "Parchim",
    "Wismar",
    "Szczecin-Goleniow",
    "Bornholm",
    "Lubeck",
    "Barth",
}
CARRIER_NAME = "CVN-75 Harry S. Truman"


def _theater() -> tuple[Campaign, ConflictTheater]:
    campaign = Campaign.from_file(YAML)
    return campaign, campaign.load_theater(campaign.advanced_iads)


def test_campaign_loads_with_expected_control_points(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    _, theater = _theater()
    names = {cp.name for cp in theater.controlpoints}
    assert BLUE_FIELDS <= names, f"missing blue fields: {BLUE_FIELDS - names}"
    assert RED_FIELDS <= names, f"missing red fields: {RED_FIELDS - names}"
    assert CARRIER_NAME in names, "carrier control point missing / renamed"


def test_ownership(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    _, theater = _theater()
    by_name = {cp.name: cp for cp in theater.controlpoints}
    for name in BLUE_FIELDS | {CARRIER_NAME}:
        assert by_name[name].starting_coalition.is_blue, f"{name} must start BLUE"
    for name in RED_FIELDS:
        assert by_name[name].starting_coalition.is_red, f"{name} must start RED"


def test_air_wing_binds_including_the_carrier(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    campaign, theater = _theater()
    awc = campaign.load_air_wing_config(theater)
    by_name = {cp.name: squadrons for cp, squadrons in awc.by_location.items()}
    # The carrier wing keys off the carrier's NAME string (not a numeric id).
    assert CARRIER_NAME in by_name, "carrier air wing did not bind -- name-key drift"
    assert len(by_name[CARRIER_NAME]) == 6, "carrier should field 6 squadrons"
    # Nordholz = the 414th land wing (F-22 + F-15E).
    nordholz_types = {s.aircraft_type for s in by_name["Nordholz"] if s.aircraft_type}
    assert any("F-22" in t for t in nordholz_types)
    assert any("F-15E" in t for t in nordholz_types)


def test_iads_coastal_naval_belt(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    _, theater = _theater()
    belt: Counter[str] = Counter()
    for cp in theater.controlpoints:
        pl = cp.preset_locations
        for attr in (
            "long_range_sams",
            "medium_range_sams",
            "short_range_sams",
            "coastal_defenses",
            "ewrs",
            "missile_sites",
            "ships",
            "iads_command_center",
            "iads_connection_node",
            "iads_power_source",
            "factories",
            "ammunition_depots",
        ):
            belt[attr] += len(getattr(pl, attr))
    assert belt["long_range_sams"] == 11, "S-400 regiments + S-300 nodes"
    assert belt["medium_range_sams"] == 4, "forward MERAD screen"
    assert belt["short_range_sams"] == 9, "per-base point defense"
    assert belt["coastal_defenses"] == 5, "coastal anti-ship wall"
    assert belt["ewrs"] == 5
    assert belt["missile_sites"] == 1, "coastal SS-26 (SCUD hunt)"
    assert belt["ships"] == 3, "Baltic Fleet SAG"
    # advanced-IADS C2 cells (one trio per red hub).
    assert belt["iads_command_center"] == 4
    assert belt["iads_connection_node"] == 4
    assert belt["iads_power_source"] == 4
    assert belt["factories"] == 3
    assert belt["ammunition_depots"] == 3


def test_no_markers_leak_onto_the_spare_neutral_fields(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    _, theater = _theater()
    spares = {"Bienenfarm", "H FRG 09", "H FRG 12"}
    for cp in theater.controlpoints:
        if cp.name not in spares:
            continue
        pl = cp.preset_locations
        leaked = [
            attr
            for attr in dir(pl)
            if not attr.startswith("_")
            and isinstance(getattr(pl, attr), list)
            and getattr(pl, attr)
        ]
        assert not leaked, f"{cp.name} (inert spare) caught markers: {leaked}"


def test_victory_parses() -> None:
    data = yaml.safe_load(YAML.read_text(encoding="utf-8"))
    victory = parse_victory(data.get("victory"))
    assert victory is not None
    assert victory.win_when[0].capture_cps == ("Kastrup",)  # liberate Copenhagen
    assert victory.lose_when[0].lose_cps == ("Nordholz",)  # lose the bridgehead


# --- The NATO Baltic 2027 coalition faction (Sweden + UK allied contingents) -----------
#
# The campaign's blue side is a purpose-built coalition faction rather than plain
# `USA 2020`: Sweden joined NATO in 2024 and the campaign fights in its home water,
# and the UK leads the Joint Expeditionary Force. The risk these pins cover is the
# fork's documented silent-drop path -- `Faction.from_dict` DISCARDS a unit string it
# cannot resolve, so a pack rename (the CH 1.5.0 wave renamed ids wholesale) would
# quietly empty the allied contingents instead of failing, and the campaign would still
# load looking fine.

FACTION_JSON = Path("resources/factions/nato_baltic_2027.json")
FACTION_NAME = "NATO Baltic 2027"

if TYPE_CHECKING:
    from game.factions.faction import Faction

# One signature unit per allied capability the coalition exists to provide.
SWEDISH_CONTRIBUTION = {
    "[CH] Visby Class Corvette",  # Baltic archipelago littoral
    "[CH] Strv 122 MBT",
    "[CH] UndE 23 (RBS 70/90/98) STR",
}
UK_CONTRIBUTION = {
    "[CH] Type 45 Destroyer",  # carrier-screen area air defence
    "[CH] Type 26 Frigate",
    "[CH] Challenger 3 MBT",
    "[CH] Sky Sabre C2 (HX)",
}
# Preset SAM/coastal sites the allies bring that plain USA 2020 cannot field.
ALLIED_PRESETS = {
    "RBS-15",  # blue coastal anti-ship -- the mirror of red's Bastion/Bal belt
    "LvS-103 Rb103B",  # Swedish long-range area SAM
    "Sky Sabre Battery",  # UK point defence for recaptured fields
}


def _faction() -> "Faction":
    import json

    from game.factions.faction import Faction

    return Faction.from_dict(json.loads(FACTION_JSON.read_text(encoding="utf-8")))


def test_campaign_flies_the_coalition_faction() -> None:
    data = yaml.safe_load(YAML.read_text(encoding="utf-8"))
    assert data["recommended_player_faction"] == FACTION_NAME
    # The allied units are mod-gated: a missing pack STRIPS them from the faction, so
    # the campaign must preseed both packs or the contingents silently never appear.
    settings = data["settings"]
    assert settings["swedishmilitaryassetspack"] is True
    assert settings["ukmilitaryassetspack"] is True
    assert settings["usamilitaryassetspack"] is True


def test_no_faction_unit_string_is_silently_dropped(tmp_path: Path) -> None:
    """Every authored string must resolve -- the CH-rename silent-drop guard."""
    persistency.setup(str(tmp_path), False, 0)
    import json

    authored = json.loads(FACTION_JSON.read_text(encoding="utf-8"))
    faction = _faction()
    for json_key, attr in [
        ("aircrafts", "aircraft"),
        ("frontline_units", "frontline_units"),
        ("artillery_units", "artillery_units"),
        ("infantry_units", "infantry_units"),
        ("logistics_units", "logistics_units"),
        ("naval_units", "naval_units"),
        ("air_defense_units", "air_defense_units"),
        ("preset_groups", "preset_groups"),
        ("missiles", "missiles"),
    ]:
        want = len(dict.fromkeys(authored.get(json_key, [])))
        got = len(getattr(faction, attr))
        assert got >= want, (
            f"{json_key}: {want - got} string(s) silently dropped -- a unit id was "
            f"renamed or the pack is not registered"
        )


def test_allied_contingents_are_present(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    faction = _faction()
    fielded = {u.display_name for u in faction.frontline_units}
    fielded |= {u.display_name for u in faction.naval_units}
    fielded |= {u.display_name for u in faction.air_defense_units}
    missing = (SWEDISH_CONTRIBUTION | UK_CONTRIBUTION) - fielded
    assert not missing, f"allied contingent lost units: {sorted(missing)}"

    presets = {g.name for g in faction.preset_groups}
    assert (
        ALLIED_PRESETS <= presets
    ), f"missing allied sites: {ALLIED_PRESETS - presets}"


def test_faction_degrades_cleanly_with_the_mods_off(tmp_path: Path) -> None:
    """Mods off must strip the allied units, not crash -- the eject-path guard."""
    persistency.setup(str(tmp_path), False, 0)
    from game.theater.start_generator import ModSettings

    faction = _faction()
    before = len(faction.frontline_units)
    faction.apply_mod_settings(ModSettings())  # every mod toggle off
    after = len(faction.frontline_units)
    assert after < before, "mods-off did not strip the CH units"
    assert after > 0, "mods-off stripped the vanilla core too"
    assert not any(u.display_name.startswith("[CH]") for u in faction.frontline_units)


def test_swedish_gripen_squadron_is_authored_and_country_pinned() -> None:
    """The Gripen is blue's dedicated DEAD unit -- and its own mod gate is subtle.

    ``CH_JAS39C`` ships INSIDE the CurrentHill Sweden pack and is gated by
    ``swedishmilitaryassetspack``; the separate ``jas39_gripen`` ModSetting gates the
    community mod's unrelated ``JAS39Gripen`` airframe. Preseeding the wrong one would
    strip this squadron silently, so pin the pairing.
    """
    data = yaml.safe_load(YAML.read_text(encoding="utf-8"))
    nordholz = data["squadrons"][47]
    gripens = [s for s in nordholz if s.get("aircraft_type") == "[CH] JAS 39C Gripen"]
    assert len(gripens) == 1, "the Swedish Gripen squadron is missing from Nordholz"
    squadron = gripens[0]
    # §23: without the country pin it flies under the shared US voice.
    assert squadron["country"] == "Sweden"
    # Blue's only other dedicated SEAD/DEAD unit is the carrier Growler squadron.
    assert squadron["primary"] == "DEAD"
    assert data["settings"]["swedishmilitaryassetspack"] is True


def test_gripen_is_fielded_and_is_a_dead_platform(tmp_path: Path) -> None:
    persistency.setup(str(tmp_path), False, 0)
    from game.ato.flighttype import FlightType

    faction = _faction()
    gripen = [a for a in faction.aircraft if a.display_name == "[CH] JAS 39C Gripen"]
    assert gripen, "the Gripen was dropped from the faction"
    assert gripen[0].dcs_unit_type.id == "CH_JAS39C"
    # The unit data rates it top of its own file for DEAD; if that regresses the
    # squadron above would still bind but would stop being the SEAD answer.
    assert gripen[0].task_priority(FlightType.DEAD) >= 700


def test_finnish_hornet_squadron_closes_the_barcap_hole() -> None:
    """Blue flew ZERO BARCAP against red's six until this squadron.

    Finland joined NATO in April 2023 and its Hornets are interceptors, so BARCAP is
    both the historically honest role and the gap in the order of battle. It sits at
    Hamburg because that is blue's most exposed field (~53 km from the nearest red
    base) and had no fast air at all.
    """
    data = yaml.safe_load(YAML.read_text(encoding="utf-8"))
    hamburg = data["squadrons"][17]
    finns = [s for s in hamburg if s.get("country") == "Finland"]
    assert len(finns) == 1, "the Finnish Hornet squadron is missing from Hamburg"
    squadron = finns[0]
    assert squadron["aircraft_type"] == "F/A-18C Hornet (Lot 20)"
    assert squadron["primary"] == "BARCAP"

    # The hole it exists to close: blue must field at least one BARCAP squadron.
    blue_bases = [47, 5, 17, CARRIER_NAME]
    barcaps = [
        s
        for base in blue_bases
        for s in data["squadrons"].get(base, [])
        if s["primary"] == "BARCAP"
    ]
    assert barcaps, "blue has no BARCAP squadron -- the Finnish detachment was dropped"
