"""Generate the Qt stylesheet from the design tokens.

Replaces the hand-maintained ``style-dcs.css``, in which every colour was a
literal and the same grey appeared under several spellings. Every rule below is
derived from :mod:`qt_ui.theme.tokens`, so a palette change is one edit.

This is a faithful superset of the sheet it replaces: every widget selector and
every ``style="..."`` property hook the old sheet carried is still styled, so no
screen loses its look. It additionally styles widgets the old sheet never
covered — scrollbar handles, radio buttons, sliders, tooltips, the status bar,
splitter handles, list/table rows and focus states — which previously fell
through to the platform default and read as unthemed.
"""

from __future__ import annotations

from qt_ui.theme.tokens import RETRIBUTION_DARK, SCALE, Palette, Scale

# Task chips, grouped so the categories stay decodable at a glance. Every member
# of FlightType is covered: the old sheet styled only 10 of 27, so the rest drew
# as plain text with no chip at all.
_A2A = ("BARCAP", "TARCAP", "SWEEP", "ESCORT")
_INTERCEPT = ("INTERCEPTION",)
_A2G = (
    "CAS",
    "BAI",
    "ANTISHIP",
    "STRIKE",
    "OCA_RUNWAY",
    "OCA_AIRCRAFT",
    "ARMED_RECON",
    "SCAR",
)
_DEAD = ("DEAD", "SEAD_SWEEP")
_SEAD = ("SEAD", "SEAD_ESCORT")
_EW = ("JAMMING", "ESCORT_JAMMER")
_RECON = ("TARPS",)
_SUPPORT = ("AEWC", "REFUELING", "TRANSPORT", "FERRY", "RECOVERY", "AIR_ASSAULT")
_RESCUE = ("COMBAT_SAR",)

_TASK_GROUPS = (
    (_A2A, "#4A5BA8"),
    (_INTERCEPT, "#7A57C0"),
    (_A2G, "#A8324C"),
    (_DEAD, "#C08540"),
    (_SEAD, "#A67638"),
    (_EW, "#35707D"),
    (_RECON, "#4E7A5E"),
    (_SUPPORT, "#46545F"),
    (_RESCUE, "#B5652E"),
)


def task_chip_colors() -> dict[str, str]:
    """Flight-task name -> chip colour, for tests and any non-QSS consumer."""
    colors: dict[str, str] = {}
    for names, color in _TASK_GROUPS:
        for name in names:
            colors[name] = color
    return colors


def _task_chips(p: Palette, s: Scale) -> str:
    rules = []
    for names, color in _TASK_GROUPS:
        selector = ", ".join(f'QLabel[style="{name}"]' for name in names)
        rules.append(
            f"{selector} {{\n"
            f"    background-color: {color};\n"
            f"    color: {p.text};\n"
            f"    border: none;\n"
            f"    border-radius: {s.radius_sm}px;\n"
            f"    padding: {s.space_1}px {s.space_3}px;\n"
            f"    font-weight: 600;\n"
            f"}}"
        )
    return "\n".join(rules)


def build_stylesheet(p: Palette = RETRIBUTION_DARK, s: Scale = SCALE) -> str:
    """Build the complete application stylesheet."""
    return "\n".join(
        [
            _base(p, s),
            _chrome(p, s),
            _buttons(p, s),
            _labels(p, s),
            _task_chips(p, s),
            _containers(p, s),
            _inputs(p, s),
            _views(p, s),
            _finances(p, s),
            _panel_overrides(p, s),
            _legacy_classes(p, s),
        ]
    )


def _base(p: Palette, s: Scale) -> str:
    return f"""
/* ==========================================================================
   Generated by qt_ui/theme/qss.py — do not hand-edit.
   Change qt_ui/theme/tokens.py instead.
   ========================================================================== */

QWidget {{
    background-color: {p.ground};
    color: {p.text};
}}

QLiberationWindow {{
    background-color: {p.ground};
    color: {p.text};
}}

QDialog {{
    background-color: {p.ground};
}}

/* Keep message box text selectable. https://stackoverflow.com/a/32595502/632035 */
QMessageBox {{
    messagebox-text-interaction-flags: 5;
}}

QToolTip {{
    background-color: {p.chrome};
    color: {p.text};
    border: 1px solid {p.line_strong};
    padding: {s.space_2}px {s.space_3}px;
}}

QStatusBar {{
    background: {p.chrome};
    color: {p.text_dim};
    border-top: 1px solid {p.line};
}}

QSplitter::handle {{
    background: {p.line};
}}
QSplitter::handle:horizontal {{ width: 1px; }}
QSplitter::handle:vertical {{ height: 1px; }}
QSplitter::handle:hover {{ background: {p.accent}; }}
"""


def _chrome(p: Palette, s: Scale) -> str:
    return f"""
QMenuBar {{
    background: {p.chrome};
    spacing: {s.space_1}px;
    border-bottom: 1px solid {p.line};
}}
QMenuBar::item {{
    padding: {s.space_2}px {s.space_5}px;
    background: transparent;
    border-radius: {s.radius_sm}px;
    margin: {s.space_2}px 0;
    color: {p.text_dim};
}}
QMenuBar::item:selected, QMenuBar::item:pressed {{
    background: {p.raised};
    color: {p.text};
}}

QMenu {{
    background: {p.panel};
    border: 1px solid {p.line_strong};
    padding: {s.space_2}px;
}}
QMenu::item {{
    padding: {s.space_3}px {s.space_6}px;
    color: {p.text_dim};
}}
QMenu::item:selected {{
    background: {p.accent};
    color: {p.on_accent};
}}
QMenu::separator {{
    height: 1px;
    background: {p.line};
    margin: {s.space_2}px {s.space_3}px;
}}

QToolBar {{
    background: {p.chrome};
    border: none;
    border-bottom: 1px solid {p.line};
    padding: {s.space_2}px {s.space_3}px;
    spacing: {s.space_2}px;
}}
QToolBar::separator {{
    background: {p.line_strong};
    width: 1px;
    margin: {s.space_2}px {s.space_3}px;
}}

QToolButton {{
    background: transparent;
    border: 1px solid transparent;
    border-radius: {s.radius_sm}px;
    padding: {s.space_2}px {s.space_3}px;
    color: {p.text_dim};
}}
QToolButton:hover {{
    background: {p.raised};
    border-color: {p.line_strong};
    color: {p.text};
}}
QToolButton:checked {{
    background: {p.raised};
    border-color: {p.accent};
    color: {p.text};
}}

/* The campaign status strip. Values read loud, their labels read quiet — the
   old sheet made every descendant bold 12px, so nothing had rank. */
QTopPanel {{
    background-color: {p.chrome};
    border-bottom: 1px solid {p.line};
}}
QTopPanel * {{
    background-color: {p.chrome};
    color: {p.text_dim};
    font-size: {s.text_md}px;
}}
QTopPanel QGroupBox {{
    border: none;
    margin: 0;
    padding: {s.space_1}px {s.space_4}px;
}}
QTopPanel QGroupBox::title {{
    font-size: {s.text_xs}px;
    font-weight: 600;
    color: {p.text_faint};
    padding: 0;
}}
"""


def _buttons(p: Palette, s: Scale) -> str:
    return f"""
QPushButton {{
    background: {p.raised};
    border: 1px solid {p.line_strong};
    color: {p.text};
    padding: {s.control_padding_y}px {s.control_padding_x}px;
    border-radius: {s.radius}px;
}}
QPushButton:hover {{
    background: {p.line_strong};
    border-color: {p.text_faint};
}}
QPushButton:pressed {{
    background: {p.panel};
}}
QPushButton:disabled {{
    background: {p.panel};
    color: {p.text_faint};
    border-color: {p.line};
}}
QPushButton:focus {{
    border-color: {p.accent};
}}

/* The primary action. Exactly one of these should be visible at a time — it is
   what makes "Take off" findable among a row of otherwise identical buttons. */
QPushButton[style="btn-primary"] {{
    background: {p.accent};
    border: 1px solid {p.accent};
    color: {p.on_accent};
    padding: {s.control_padding_y}px {s.control_padding_x}px;
    border-radius: {s.radius}px;
    font-weight: 700;
}}
QPushButton[style="btn-primary"]:hover {{
    background: {p.accent_hover};
    border-color: {p.accent_hover};
}}
QPushButton[style="btn-primary"]:pressed {{
    background: {p.accent_press};
}}

QPushButton[style="btn-success"], QPushButton[style="start-button"] {{
    background-color: {p.success};
    border: 1px solid {p.success};
    color: {p.on_accent};
    border-radius: {s.radius}px;
    font-weight: 600;
}}
QPushButton[style="start-button"] {{
    padding: {s.space_4}px {s.space_7}px;
}}
QPushButton[style="btn-success"]:hover, QPushButton[style="start-button"]:hover {{
    background: {p.success_hover};
    border-color: {p.success_hover};
}}

QPushButton[style="btn-buy"] {{
    background-color: {p.success};
    border: 1px solid {p.success};
    color: {p.on_accent};
    border-radius: {s.radius_sm}px;
    font-weight: 600;
    margin: 0px;
    padding: {s.space_1}px {s.space_2}px;
}}
QPushButton[style="btn-buy"]:hover {{
    background: {p.success_hover};
}}

QPushButton[style="btn-sell"] {{
    background-color: {p.danger};
    border: 1px solid {p.danger};
    color: {p.on_accent};
    border-radius: {s.radius_sm}px;
    font-weight: 600;
    margin: 0px;
    padding: {s.space_1}px {s.space_2}px;
}}
QPushButton[style="btn-sell"]:hover {{
    background: {p.danger_hover};
}}

QPushButton[style="btn-info"] {{
    background-color: {p.raised};
    border: 1px solid {p.line_strong};
    color: {p.accent};
    border-radius: {s.radius_sm}px;
    font-weight: 700;
    margin: 0px;
    padding: {s.space_1}px {s.space_2}px;
}}
QPushButton[style="btn-info"]:hover {{
    border-color: {p.accent};
    color: {p.accent_hover};
}}

QPushButton[style="btn-danger"] {{
    background-color: {p.danger};
    color: {p.on_accent};
    padding: {s.control_padding_y}px {s.control_padding_x}px;
    border-radius: {s.radius}px;
    border: 1px solid {p.danger};
}}
QPushButton[style="btn-danger"]:hover {{
    background-color: {p.danger_hover};
}}

QPushButton[style="btn-accept"] {{
    background-color: {p.success};
    color: {p.on_accent};
    padding: {s.control_padding_y}px {s.control_padding_x}px;
    border-radius: {s.radius}px;
    border: 1px solid {p.success};
}}
QPushButton[style="btn-accept"]:hover {{
    background-color: {p.success_hover};
}}

/* Finances: ON/OFF pills that write their setting directly. */
QPushButton[style="pill-on"] {{
    border: 1px solid {p.success};
    color: {p.success};
    background: transparent;
    padding: {s.space_1}px {s.space_5}px;
    font-weight: 700;
}}
QPushButton[style="pill-on"]:hover {{ background: {p.raised}; }}
QPushButton[style="pill-off"] {{
    border: 1px solid {p.line_strong};
    color: {p.text_faint};
    background: transparent;
    padding: {s.space_1}px {s.space_5}px;
    font-weight: 700;
}}
QPushButton[style="pill-off"]:hover {{ background: {p.raised}; }}

/* Collapsible section header — arrow and title, no button chrome. */
QPushButton[style="disclosure"] {{
    border: none;
    background: transparent;
    color: {p.text_dim};
    font-weight: 700;
    text-align: left;
    padding: {s.space_2}px {s.space_1}px;
}}
QPushButton[style="disclosure"]:hover {{ color: {p.text}; }}
"""


def _labels(p: Palette, s: Scale) -> str:
    return f"""
QLabel {{
    background: transparent;
    border: none;
    font-weight: normal;
}}
QLabel:disabled {{
    color: {p.text_faint};
}}

QLabel[style="base-title"] {{
    font-size: {s.text_2xl}px;
    font-weight: 600;
    color: {p.text};
}}
QLabel[style="budget-label"] {{
    font-size: {s.text_lg}px;
    margin-right: {s.space_7}px;
}}

QLabel[style="icon-plane"] {{
    background-color: {p.raised};
    border: 1px solid {p.line_strong};
    border-radius: {s.radius_sm}px;
    min-height: 24px;
    max-width: 84px;
    color: {p.text};
}}
QLabel[style="icon-armor"] {{
    background-color: {p.raised};
    border: 1px solid {p.line_strong};
    border-radius: {s.radius_sm}px;
    min-height: 24px;
    max-width: 64px;
    color: {p.text};
}}

QLabel[style="info-element"] {{
    border: 1px solid {p.line};
    border-radius: {s.radius_sm}px;
    color: {p.text};
    padding: {s.space_1}px {s.space_3}px;
}}
QTextBrowser[style="info-desc"] {{
    border: 1px solid {p.line};
    border-radius: {s.radius_sm}px;
    color: {p.text};
    padding: {s.space_1}px {s.space_3}px;
}}

/* An urgent line -- something on a clock the player should act on this turn
   (§83's evading aviators). Amber is the fork's established "pay attention"
   colour on the map and the kneeboard; the chrome accent is deliberately not
   amber, so this never competes with it. */
QLabel[style="warning"] {{
    color: {p.warning};
    font-weight: 600;
}}

QLabel[style="small"], QLabel[style="text-xs"] {{ font-size: {s.text_xs}px; }}
QLabel[style="text-sm"] {{ font-size: {s.text_sm}px; }}
QLabel[style="text-md"] {{ font-size: {s.text_md}px; }}
QLabel[style="text-xl"] {{ font-size: {s.text_lg}px; }}
"""


def _finances(p: Palette, s: Scale) -> str:
    return f"""
QLabel[style="green"]   {{ color: {p.success}; font-weight: 700; }}
QLabel[style="expense"] {{ color: {p.danger}; font-weight: 700; }}
QLabel[style="muted"]   {{ color: {p.text_faint}; }}
QLabel[style="balance"] {{ color: {p.accent}; font-weight: 700; }}
QLabel[style="net"] {{
    font-size: {s.text_xl}px;
    font-weight: 800;
    color: {p.success};
}}
QLabel[style="net-neg"] {{
    font-size: {s.text_xl}px;
    font-weight: 800;
    color: {p.danger};
}}

QFrame[style="summary-box"] {{
    background-color: {p.panel};
    border: 1px solid {p.line};
    border-radius: {s.radius}px;
}}
QFrame[style="summary-box"] QLabel {{ background: transparent; }}
"""


def _containers(p: Palette, s: Scale) -> str:
    return f"""
QGroupBox {{
    margin-top: 1ex;
    border: 1px solid {p.line};
    border-radius: {s.radius}px;
    padding: {s.space_3}px;
    margin: {s.space_3}px;
}}
QGroupBox[style="buy-box"] {{
    padding: 0px;
    margin: 0px;
}}
QGroupBox::title {{
    subcontrol-origin: margin;
    subcontrol-position: top left;
    padding: {s.space_2}px {s.space_3}px;
    color: {p.text_dim};
    font-weight: 700;
}}

QTabWidget::pane {{
    border: 1px solid {p.line};
    background: {p.ground};
}}
QTabBar::tab {{
    color: {p.text_faint};
    background: {p.panel};
    border: 1px solid {p.line};
    border-bottom: none;
    border-top-left-radius: {s.radius}px;
    border-top-right-radius: {s.radius}px;
    min-width: 8ex;
    padding: {s.space_3}px {s.space_5}px;
    margin-right: {s.space_1}px;
}}
QTabBar::tab:hover {{
    background: {p.raised};
    color: {p.text};
}}
QTabBar::tab:selected {{
    color: {p.text};
    background: {p.ground};
    border-color: {p.line_strong};
}}

QScrollBar:vertical {{
    background: {p.ground};
    width: 11px;
    margin: 0;
}}
QScrollBar:horizontal {{
    background: {p.ground};
    height: 11px;
    margin: 0;
}}
QScrollBar::handle:vertical, QScrollBar::handle:horizontal {{
    background: {p.line_strong};
    border-radius: 5px;
    min-height: 24px;
    min-width: 24px;
}}
QScrollBar::handle:hover {{ background: {p.text_faint}; }}
QScrollBar::add-line, QScrollBar::sub-line {{
    height: 0; width: 0; border: none; background: none;
}}
QScrollBar::add-page, QScrollBar::sub-page {{ background: none; }}
"""


def _inputs(p: Palette, s: Scale) -> str:
    return f"""
QComboBox {{
    border: 1px solid {p.line_strong};
    border-radius: {s.radius}px;
    color: {p.text};
    padding: {s.space_2}px {s.space_5}px;
    background: {p.raised};
}}
QComboBox:hover {{ border-color: {p.accent}; }}
QComboBox:focus {{ border-color: {p.accent}; }}
QComboBox:disabled, QComboBox::drop-down:disabled {{
    color: {p.text_faint};
    background: {p.panel};
}}
QComboBox::drop-down {{
    subcontrol-origin: padding;
    subcontrol-position: top right;
    padding: {s.space_1}px;
    border: none;
    width: 18px;
}}
QComboBox::down-arrow {{
    image: url(resources/stylesheets/chevron-down.png);
}}
QComboBox QAbstractItemView {{
    padding: {s.space_2}px;
    border: 1px solid {p.line_strong};
    background: {p.panel};
    selection-background-color: {p.accent};
    selection-color: {p.on_accent};
}}

QSpinBox, QDoubleSpinBox {{
    border: 1px solid {p.line_strong};
    border-radius: {s.radius}px;
    color: {p.text};
    padding: {s.space_2}px {s.space_5}px;
    background: {p.raised};
    min-width: 40px;
}}
QSpinBox:hover, QDoubleSpinBox:hover,
QSpinBox:focus, QDoubleSpinBox:focus {{
    border-color: {p.accent};
}}
QSpinBox::up-button, QSpinBox::down-button,
QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {{
    border: none;
    background: transparent;
    width: 16px;
}}
QSpinBox::up-button, QDoubleSpinBox::up-button {{
    image: url(resources/stylesheets/chevron-up.png);
}}
QSpinBox::down-button, QDoubleSpinBox::down-button {{
    image: url(resources/stylesheets/chevron-down.png);
}}

QLineEdit, QTimeEdit, QDateTimeEdit, QDateEdit {{
    padding: {s.space_2}px {s.space_5}px;
    border: 1px solid {p.line_strong};
    border-radius: {s.radius}px;
    background: {p.raised};
    color: {p.text};
    selection-background-color: {p.accent};
    selection-color: {p.on_accent};
}}
QLineEdit:focus, QTimeEdit:focus, QDateTimeEdit:focus, QDateEdit:focus {{
    border-color: {p.accent};
}}
QLineEdit:disabled {{
    background: {p.panel};
    color: {p.text_faint};
}}

/* Notes and Logs previously hard-coded their own background inline. */
QTextEdit, QPlainTextEdit, QTextBrowser {{
    background: {p.panel};
    border: 1px solid {p.line};
    border-radius: {s.radius}px;
    color: {p.text};
    selection-background-color: {p.accent};
    selection-color: {p.on_accent};
}}

QGroupBox::indicator, QCheckBox::indicator {{
    width: {s.indicator}px;
    height: {s.indicator}px;
    border: 1px solid {p.line_strong};
    border-radius: {s.radius_sm}px;
    background: {p.raised};
}}
QGroupBox::indicator:hover, QCheckBox::indicator:hover {{
    border-color: {p.accent};
    image: url(resources/stylesheets/check-hover.png);
}}
QGroupBox::indicator:checked, QCheckBox::indicator:checked {{
    background: {p.accent};
    border-color: {p.accent};
    image: url(resources/stylesheets/check.png);
}}
QCheckBox:disabled {{ color: {p.text_faint}; }}
QCheckBox::indicator:disabled {{
    background: {p.panel};
    border-color: {p.line};
}}

/* Radio buttons were never styled — the New Game wizard is built from them. */
QRadioButton {{ spacing: {s.space_3}px; }}
QRadioButton::indicator {{
    width: {s.indicator}px;
    height: {s.indicator}px;
    border: 1px solid {p.line_strong};
    /* Half the box, not the whole box — a radius equal to the width does not
       round in Qt and the control draws as a square, i.e. as a checkbox. */
    border-radius: {s.indicator // 2}px;
    background: {p.raised};
}}
QRadioButton::indicator:hover {{ border-color: {p.accent}; }}
/* The dot is drawn as a radial gradient rather than a thick border. Setting the
   `border` shorthand in this state resets border-radius — even if the radius is
   restated — and the control squares off into something indistinguishable from
   a checkbox. Touching only border-color and background keeps the base rule's
   radius intact. */
QRadioButton::indicator:checked {{
    border-color: {p.accent};
    background: qradialgradient(
        cx: 0.5, cy: 0.5, radius: 0.5, fx: 0.5, fy: 0.5,
        stop: 0 {p.accent}, stop: 0.5 {p.accent}, stop: 0.55 {p.raised}
    );
}}
QRadioButton:disabled {{ color: {p.text_faint}; }}

/* Sliders were never styled — every FloatSpinSlider setting uses one. */
QSlider::groove:horizontal {{
    height: 3px;
    background: {p.line_strong};
    border-radius: 2px;
}}
QSlider::sub-page:horizontal {{
    background: {p.accent};
    border-radius: 2px;
}}
QSlider::handle:horizontal {{
    background: {p.text};
    border: none;
    width: 12px;
    height: 12px;
    margin: -5px 0;
    border-radius: 6px;
}}
QSlider::handle:horizontal:hover {{ background: {p.accent_hover}; }}

QProgressBar {{
    border: 1px solid {p.line};
    border-radius: {s.radius_sm}px;
    background: {p.panel};
    text-align: center;
    color: {p.text};
}}
QProgressBar::chunk {{
    background: {p.accent};
}}
"""


def _views(p: Palette, s: Scale) -> str:
    return f"""
QListView, QTreeView, QTableView {{
    border: 1px solid {p.line};
    border-radius: {s.radius}px;
    background-color: {p.panel};
    alternate-background-color: {p.ground};
    selection-background-color: {p.accent};
    selection-color: {p.on_accent};
    outline: none;
}}
QListView::item, QTreeView::item, QTableView::item {{
    padding: {s.space_1}px;
    border: none;
}}
QListView::item:hover, QTreeView::item:hover, QTableView::item:hover {{
    background: {p.raised};
}}
QListView::item:selected, QTreeView::item:selected, QTableView::item:selected {{
    background: {p.accent};
    color: {p.on_accent};
}}

QHeaderView {{ background: {p.chrome}; }}
QHeaderView::section {{
    background: {p.chrome};
    color: {p.text_dim};
    padding: {s.space_2}px {s.space_3}px;
    border: none;
    border-right: 1px solid {p.line};
    border-bottom: 1px solid {p.line};
    font-weight: 600;
}}
QHeaderView::section:horizontal, QHeaderView::section:vertical {{
    text-align: left;
}}
QTableView QTableCornerButton::section {{
    background: {p.chrome};
    border: none;
}}

QCalendarWidget QWidget {{ color: {p.text_dim}; }}
QCalendarWidget QAbstractItemView {{
    background-color: {p.panel};
    border: 1px solid {p.line};
    selection-background-color: {p.accent};
    selection-color: {p.on_accent};
}}
QCalendarWidget QTableView {{
    background-color: {p.panel};
    border: 1px solid {p.line};
}}
"""


def _panel_overrides(p: Palette, s: Scale) -> str:
    return f"""
QFrame[style="QConditionsWidget"] {{
    margin: 0px;
    border: 1px solid transparent;
    border-radius: {s.radius}px;
    padding: 0px;
    background: transparent;
}}
QFrame[style="QConditionsWidget"]:hover {{
    background: {p.raised};
    border-color: {p.line_strong};
}}

QGroupBox[style="QWeatherWidget"] {{
    padding: 0px;
    margin-left: 0px;
    margin-right: {s.space_3}px;
    margin-top: 1px;
    margin-bottom: {s.space_3}px;
    border: none;
}}
QGroupBox[style="QWeatherWidget"] QLabel[style="text-sm"] {{
    padding: 0px;
    margin: 0px;
    font-size: {s.text_xs}px;
}}

QGroupBox[style="IntelSummary"] {{
    padding-left: {s.space_7}px;
    padding-right: 0px;
    padding-top: 0px;
    padding-bottom: 0px;
    margin-left: 0px;
    margin-right: {s.space_3}px;
    margin-top: 1px;
    margin-bottom: {s.space_3}px;
}}
QGroupBox[style="IntelSummary"] QLabel {{
    padding: 0px;
    margin: 0px;
    font-size: {s.text_xs}px;
    color: {p.text};
    background: transparent;
}}

QWidget[style="baseMenuHeader"] {{
    background: {p.panel};
}}
"""


def _legacy_classes(p: Palette, s: Scale) -> str:
    """Helper modifiers and the plain-class selectors the old sheet carried."""
    return f"""
*[style="no-border"] {{ border: none; }}
*[style="bordered"] {{ border: 1px solid {p.line}; }}

.tacan-edit {{
    background: {p.raised};
}}

.btn-danger {{
    background-color: {p.danger};
    color: {p.on_accent};
    padding: {s.control_padding_y}px {s.control_padding_x}px;
    border-radius: {s.radius}px;
    border: 1px solid {p.danger};
}}
.btn-danger:hover {{
    background-color: {p.danger_hover};
}}

.comms {{
    padding: {s.space_1}px;
}}

.hidden {{
    visibility: hidden;
}}
"""
