"""Design tokens for the Retribution UI.

The single source of truth for colour, spacing, type size and radius.

Before this module the visual language lived as ~700 lines of literal hex in
``resources/stylesheets/style-dcs.css`` plus a second, unrelated set of literals
in the web client, so the two halves of the app could never agree and every
change was a local patch. Both are now derived from the values here: the Qt
stylesheet is generated by :mod:`qt_ui.theme.qss`, and :func:`to_css_variables`
emits the same palette as CSS custom properties for the React client.

Direction chosen 2026-07-25 (see ``docs/dev/design/414th-ui-redesign-directions.md``):
cold dark ground with a cyan-teal accent. The accent is deliberately *not* amber
or orange — the campaign map already uses those semantically (suspected activity,
the FLOT, MIA pilots), and chrome must never compete with map meaning.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict


@dataclass(frozen=True)
class Palette:
    """Every colour the interface is allowed to use."""

    # Grounds, back to front.
    chrome: str  # menu/tool/status bars — the deepest surface
    ground: str  # the window itself
    panel: str  # sidebars, group boxes, list backgrounds
    raised: str  # inputs, hovered rows, the next step up from panel

    # Lines.
    line: str  # ordinary borders and separators
    line_strong: str  # emphasis borders, focus outlines at rest

    # Text.
    text: str  # primary
    text_dim: str  # labels, secondary values
    text_faint: str  # disabled, placeholder, inactive tabs

    # The one accent. Used for the primary action, selection and focus.
    accent: str
    accent_hover: str
    accent_press: str
    on_accent: str  # text drawn on an accent fill

    # Semantic status. Separate from the accent by role, never decorative.
    success: str
    success_hover: str
    danger: str
    danger_hover: str
    warning: str

    # Flight-task chips. Grouped by role so the categories stay decodable:
    # air-to-air blue, intercept violet, air-to-ground red, SEAD/DEAD amber.
    task_colors: Dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class Scale:
    """Spacing, radius and type sizes.

    Type sizes stay in ``px`` to match the sizes the app shipped with. Qt scales
    px by the device pixel ratio, so this is not the cause of the historical
    clipping; moving the type scale to ``pt`` so it follows the system font
    preference is a deliberate follow-up, not part of this pass.
    """

    # Spacing, in px. Everything in the stylesheet snaps to one of these.
    space_1: int = 2
    space_2: int = 4
    space_3: int = 6
    space_4: int = 8
    space_5: int = 12
    space_6: int = 16
    space_7: int = 24

    radius: int = 3
    radius_sm: int = 2

    # Type sizes, in px.
    text_xs: int = 9
    text_sm: int = 10
    text_md: int = 12
    text_lg: int = 14
    text_xl: int = 18
    text_2xl: int = 24

    # Control metrics.
    control_padding_y: int = 5
    control_padding_x: int = 10
    indicator: int = 14


#: Air-to-air blue, intercept violet, air-to-ground red, SEAD/DEAD amber.
#: Harmonised to one lightness so no single chip shouts over the others.
_TASK_COLORS: Dict[str, str] = {
    "BARCAP": "#4A5BA8",
    "TARCAP": "#4A5BA8",
    "CAP": "#4A5BA8",
    "INTERCEPTION": "#7A57C0",
    "CAS": "#A8324C",
    "BAI": "#A8324C",
    "ANTISHIP": "#A8324C",
    "STRIKE": "#A8324C",
    "DEAD": "#C08540",
    "SEAD": "#A67638",
}


#: The shipped theme. Cold dark ground, cyan-teal accent.
RETRIBUTION_DARK = Palette(
    chrome="#0A0E12",
    ground="#0F1419",
    panel="#141B22",
    raised="#1A222A",
    line="#232E38",
    line_strong="#2C3843",
    text="#E6EDF3",
    text_dim="#8A99A7",
    text_faint="#667381",
    accent="#38A3B8",
    accent_hover="#45BCD3",
    accent_press="#2C8697",
    on_accent="#04161A",
    success="#5FB47C",
    success_hover="#74C48F",
    danger="#D9636B",
    danger_hover="#E67D84",
    warning="#D9A441",
    task_colors=_TASK_COLORS,
)

SCALE = Scale()


def to_css_variables(palette: Palette = RETRIBUTION_DARK, scale: Scale = SCALE) -> str:
    """Emit the palette and scale as CSS custom properties.

    This is what keeps the promise that both halves of the app share one token
    source: the web client consumes the same values the Qt stylesheet is built
    from, rather than re-declaring near-identical greys of its own.
    """
    lines = [":root {"]
    for name, value in (
        ("chrome", palette.chrome),
        ("ground", palette.ground),
        ("panel", palette.panel),
        ("raised", palette.raised),
        ("line", palette.line),
        ("line-strong", palette.line_strong),
        ("text", palette.text),
        ("text-dim", palette.text_dim),
        ("text-faint", palette.text_faint),
        ("accent", palette.accent),
        ("accent-hover", palette.accent_hover),
        ("accent-press", palette.accent_press),
        ("on-accent", palette.on_accent),
        ("success", palette.success),
        ("danger", palette.danger),
        ("warning", palette.warning),
    ):
        lines.append(f"  --ret-{name}: {value};")
    for name, size in (
        ("space-1", scale.space_1),
        ("space-2", scale.space_2),
        ("space-3", scale.space_3),
        ("space-4", scale.space_4),
        ("space-5", scale.space_5),
        ("space-6", scale.space_6),
        ("space-7", scale.space_7),
        ("radius", scale.radius),
        ("text-xs", scale.text_xs),
        ("text-sm", scale.text_sm),
        ("text-md", scale.text_md),
        ("text-lg", scale.text_lg),
        ("text-xl", scale.text_xl),
        ("text-2xl", scale.text_2xl),
    ):
        lines.append(f"  --ret-{name}: {size}px;")
    lines.append("}")
    return "\n".join(lines) + "\n"
