"""Build a terrain's shipped §96 border file (``resources/borders/<terrain>.yaml``).

Borders are a property of the map, not of a campaign, so they are generated once
per terrain and every campaign on that map gets them. This is what makes §96
reach the 52 real-world-map campaigns that author no borders at all.

The file carries **geometry and an origin, nothing else**. Posture and airframe
come from the dated table at mission-generation time, so one border file is
correct in 1975 and in 2025.

Per country the tool: clips the real boundary to the map, drops sliver pieces,
simplifies to a vertex budget, converts to terrain XY, and picks an origin --
a real map airfield inside the polygon where one exists, otherwise an air-spawn
station at the polygon's representative point.

**The map's host nation is excluded** (``--host``): a border drawn around the
whole battlefield is noise, and the feature is about the countries around the war.

Usage:

    python tools/build_terrain_borders.py afghanistan \\
        --geojson-dir <dir> --host Afghanistan \\
        --countries Pakistan Iran Turkmenistan Uzbekistan Tajikistan India \\
        --clip 24 38 59.5 73

Country land shares per map -- and which ones the eyeball misses -- are measured
in ``docs/dev/design/414th-national-postures-notes.md``. Use that table for the
``--countries`` list; it caught India on Afghanistan and Saudi Arabia on Syria.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Optional

sys.path.insert(0, str(Path(__file__).resolve().parent))

from neutral_border_geo import (  # noqa: E402
    TERRAINS,
    country_polygon,
    pieces_of,
    simplify_to_budget,
    to_xy,
)
from shapely.geometry import Point as ShapelyPoint, Polygon, box  # noqa: E402

#: Air-spawn altitude for a country with no airfield inside its own border.
SPAWN_ALT_FT = 20000


def airfield_in(terrain: Any, polygon: Polygon) -> Optional[str]:
    """A real map airfield inside this polygon, if the terrain has one.

    Prefers the one furthest from the border, so an alert flight does not launch
    from a strip that is metres inside its own frontier.
    """
    best: Optional[tuple[float, str]] = None
    for airport in terrain.airport_list():
        latlng = airport.position.latlng()
        point = ShapelyPoint(latlng.lng, latlng.lat)
        if not polygon.contains(point):
            continue
        depth = polygon.exterior.distance(point)
        if best is None or depth > best[0]:
            best = (depth, airport.name)
    return best[1] if best else None


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("terrain", choices=sorted(TERRAINS))
    parser.add_argument("--geojson-dir", type=Path, required=True)
    parser.add_argument("--countries", nargs="+", required=True)
    parser.add_argument("--host", help="Map's own nation, excluded from the output")
    parser.add_argument(
        "--clip",
        nargs=4,
        type=float,
        required=True,
        metavar=("LAT_MIN", "LAT_MAX", "LON_MIN", "LON_MAX"),
    )
    parser.add_argument("--max-vertices", type=int, default=24)
    parser.add_argument("--out", type=Path, default=Path("resources/borders"))
    args = parser.parse_args()

    terrain = TERRAINS[args.terrain]()
    lat_min, lat_max, lon_min, lon_max = args.clip
    clip = box(lon_min, lat_min, lon_max, lat_max)

    lines = [
        f"# §96 border geometry for the {args.terrain} map. GENERATED by",
        "# tools/build_terrain_borders.py -- edit the tool, not this file.",
        "#",
        "# Geometry and an origin only: posture and airframe are resolved from",
        "# resources/borders/national_postures.yaml against the campaign's date,",
        "# so this file is correct in every era. A campaign that declares its own",
        "# neutral_border_defense: block overrides this file completely.",
        "#",
        f"# Clip: {lat_min} {lat_max} {lon_min} {lon_max}"
        + (f" · host nation excluded: {args.host}" if args.host else ""),
        f"terrain: {args.terrain}",
        "zones:",
    ]

    written = 0
    for name in args.countries:
        if args.host and name.lower() == args.host.lower():
            continue
        path = args.geojson_dir / f"{name.lower().replace(' ', '_')}.json"
        if not path.exists():
            print(f"  !! {name}: no geojson at {path}", file=sys.stderr)
            continue
        geom = country_polygon(json.loads(path.read_text(encoding="utf-8")))
        clipped = geom.intersection(clip)
        parts = pieces_of(clipped)
        if not parts:
            print(f"  -- {name}: nothing on this map, skipped", file=sys.stderr)
            continue
        for index, piece in enumerate(parts):
            ring = simplify_to_budget(piece, args.max_vertices)
            ring_xy = to_xy(terrain, ring)
            label = name if len(parts) == 1 else f"{name} (part {index + 1})"
            lines.append(f"  # {label} — {len(ring_xy)} vertices")
            lines.append(f"  - country: {name}")
            field = airfield_in(terrain, piece)
            if field:
                lines.append(f"    airfield: {field}")
            else:
                rep = piece.representative_point()
                x, y = to_xy(terrain, [(rep.x, rep.y)])[0]
                lines.append(f"    spawn: [{x:.0f}, {y:.0f}]")
                lines.append(f"    spawn_alt_ft: {SPAWN_ALT_FT}")
            lines.append("    border:")
            for x, y in ring_xy:
                lines.append(f"      - [{x:.0f}, {y:.0f}]")
            written += 1

    args.out.mkdir(parents=True, exist_ok=True)
    target = args.out / f"{args.terrain}.yaml"
    target.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {target} ({written} zones)")


if __name__ == "__main__":
    main()
