@echo off
REM ---------------------------------------------------------------------------
REM Push your Mission-Editor edits of Baltic Fury into the campaign the app loads.
REM
REM Workflow: edit "%USERPROFILE%\Saved Games\DCS\Missions\operation_baltic_fury.miz"
REM in the ME, save, then run this. Saved Games\Missions is the ME workspace -- it
REM is NOT a path Retribution loads from, so the edits do nothing until copied.
REM
REM Copies into the main checkout AND every .claude\worktrees\* checkout, because
REM a session working in a worktree otherwise keeps a stale miz.
REM
REM  !! READ THIS BEFORE USING !!
REM  operation_baltic_fury.miz is GENERATED by tools\build_baltic_fury_miz.py, whose
REM  laydown tables are the campaign's documented source of truth. Anything you sync
REM  with this script is DISCARDED the next time that builder runs. Use this only for
REM  quick in-ME iteration; once a change is worth keeping, port it into the builder's
REM  tables so it survives. See docs\dev\design\414th-baltic-fury-campaign-notes.md.
REM ---------------------------------------------------------------------------
setlocal

set "ROOT=%~dp0.."
set "SRC=%USERPROFILE%\Saved Games\DCS\Missions\operation_baltic_fury.miz"
set "REL=resources\campaigns\operation_baltic_fury.miz"

if not exist "%SRC%" (
    echo.
    echo   ERROR: no ME mission found at:
    echo     %SRC%
    echo.
    echo   Open the campaign miz in the Mission Editor and save it there first.
    echo.
    pause
    exit /b 1
)

set "COUNT=0"

if exist "%ROOT%\resources\campaigns\" (
    copy /Y "%SRC%" "%ROOT%\%REL%" >nul
    if errorlevel 1 (echo   FAILED: main checkout) else (echo   synced: main checkout & set /a COUNT+=1)
)

for /d %%W in ("%ROOT%\.claude\worktrees\*") do (
    if exist "%%~fW\resources\campaigns\" (
        copy /Y "%SRC%" "%%~fW\%REL%" >nul
        if errorlevel 1 (echo   FAILED: worktree %%~nxW) else (echo   synced: worktree %%~nxW & set /a COUNT+=1)
    )
)

echo.
if "%COUNT%"=="0" (
    echo   Nothing was synced -- no resources\campaigns folder found under %ROOT%.
) else (
    echo   Your Baltic Fury laydown is now IN the campaign ^(%COUNT% checkout^(s^)^).
    echo   Restart Retribution, then New Game -^> Germany - Baltic Fury.
    echo.
    echo   Remember: re-running tools\build_baltic_fury_miz.py overwrites this.
)
echo.
pause
endlocal
