"""Terrain elevation at the positions each campaign authors ground objects on.

Generated by ``scripts/derive_terrain_elevations.py`` into
``resources/terrain_elevation/<terrain>.json``, keyed by grid-rounded terrain XY.

The one consumer is the ground-marked steerpoint (targets, CAS FLOT boundaries,
flyovers). Those are planned on the deck and written as ``0``; whatever the
``RADIO`` flag beside that 0 is meant to mean, the number reaches the jet as sea
level, so a target on high ground gets a steerpoint underground. With an
elevation the same waypoint is written as a real MSL number and lands on the
ground it marks.

Coverage is deliberately partial: only positions authored into a campaign ``.miz``
are sampled. A front-line, convoy or relocated mobile target resolves to None and
keeps the old 0 -- see ``docs/dev/design/414th-terrain-elevation-notes.md``.
"""

from __future__ import annotations

import json
import logging
import threading
from pathlib import Path
from typing import TYPE_CHECKING, Dict, Optional, Tuple

from game.utils import Distance, meters

if TYPE_CHECKING:
    from dcs.mapping import Point
    from dcs.terrain.terrain import Terrain

logger = logging.getLogger(__name__)

_RESOURCES_DIR = Path(__file__).resolve().parents[2] / "resources"
_ELEVATION_DIR = _RESOURCES_DIR / "terrain_elevation"

#: How far from a sampled cell an answer is still trusted. A campaign marker is a
#: point but the layout spreads its units a few hundred metres around it, so the
#: waypoint rarely lands in the sampled cell itself. Past this, terrain can differ too
#: much to guess and the caller falls back to the old behaviour.
SEARCH_RADIUS_M = 1000

_cache: Dict[str, Optional["TerrainElevations"]] = {}
_cache_lock = threading.Lock()


class TerrainElevations:
    """One terrain's sampled points, indexed by grid cell."""

    def __init__(self, grid_m: int, points: Dict[Tuple[int, int], float]) -> None:
        self.grid_m = grid_m
        self.points = points

    def elevation_at(self, x: float, y: float) -> Optional[float]:
        """Metres AMSL at (x, y), or None when no sample is near enough."""
        gx = round(x / self.grid_m)
        gy = round(y / self.grid_m)
        exact = self.points.get((gx, gy))
        if exact is not None:
            return exact
        # Widen a ring at a time so the first hit is also close to the nearest.
        rings = max(1, round(SEARCH_RADIUS_M / self.grid_m))
        best: Optional[float] = None
        best_distance = float("inf")
        for ring in range(1, rings + 1):
            for dx in range(-ring, ring + 1):
                for dy in range(-ring, ring + 1):
                    if max(abs(dx), abs(dy)) != ring:
                        continue  # interior already searched
                    found = self.points.get((gx + dx, gy + dy))
                    if found is None:
                        continue
                    distance = (
                        ((gx + dx) * self.grid_m - x) ** 2
                        + ((gy + dy) * self.grid_m - y) ** 2
                    ) ** 0.5
                    if distance <= SEARCH_RADIUS_M and distance < best_distance:
                        best, best_distance = found, distance
            if best is not None:
                return best
        return None


def _load(terrain_name: str) -> Optional[TerrainElevations]:
    path = _ELEVATION_DIR / f"{terrain_name.lower()}.json"
    if not path.is_file():
        logger.debug("terrain_elevation: no JSON for terrain %r", terrain_name)
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        grid_m = int(data["grid_m"])
        points: Dict[Tuple[int, int], float] = {}
        for key, elevation in data["points"].items():
            x_str, y_str = key.split(",")
            points[(round(float(x_str) / grid_m), round(float(y_str) / grid_m))] = (
                float(elevation)
            )
    except (OSError, ValueError, KeyError) as exc:
        logger.warning("terrain_elevation: failed to read %s (%s); ignoring", path, exc)
        return None
    return TerrainElevations(grid_m, points)


def _for_terrain(terrain_name: str) -> Optional[TerrainElevations]:
    with _cache_lock:
        if terrain_name not in _cache:
            _cache[terrain_name] = _load(terrain_name)
        return _cache[terrain_name]


def elevation_at(terrain: "Terrain", position: "Point") -> Optional[Distance]:
    """Terrain elevation AMSL at a map position, or None when unsampled."""
    table = _for_terrain(terrain.name)
    if table is None:
        return None
    found = table.elevation_at(position.x, position.y)
    return None if found is None else meters(found)
